const core = require("@actions/core");
const github = require("@actions/github");
const exec = require("@actions/exec");
const path = require("path");
const fs = require("fs");
const { createCanvas } = require("canvas");
const { drawContributions } = require("github-contributions-canvas");

async function commitAndPush(outputPath) {
    const token = core.getInput("github_token", { required: true });
    const repo = github.context.repo; // Object containing {owner, repo}

    // 1. Setup Git User
    await exec.exec("git", [
        "config",
        "--global",
        "user.name",
        "github-actions[bot]",
    ]);
    await exec.exec("git", [
        "config",
        "--global",
        "user.email",
        "41898282+github-actions[bot]@users.noreply.github.com",
    ]);

    // 2. Prepare the Remote URL with the token for authentication
    // Format: https://x-access-token:<token>@github.com/owner/repo.git
    const remoteUrl = `https://x-access-token:${token}@github.com/${repo.owner}/${repo.repo}.git`;

    // 3. Add, Commit, and Push
    await exec.exec("git", ["add", outputPath]);

    try {
        // Only commit if there are changes to avoid workflow errors
        await exec.exec("git", [
            "commit",
            "-m",
            "chore: update contribution stats [skip ci]",
        ]);

        // Push using the authenticated URL
        await exec.exec("git", [
            "push",
            remoteUrl,
            `HEAD:${github.context.ref}`,
        ]);

        core.info("Changes pushed successfully.");
    } catch (error) {
        core.error(`Failed to push changes: ${error.message}`);
    }
}

async function run() {
    try {
        let username = core.getInput("username") || github.context.repo.owner;
        const theme = core.getInput("theme");
        const outputPath = core.getInput("output_path");
        const isDryRun = core.getInput("dryrun") === "true";

        core.info(`Fetching data for ${username}...`);

        const response = await fetch(
            `https://github-contributions.vercel.app/api/v1/${username}`,
        );
        const data = await response.json();

        const canvasEl = createCanvas(1000, 1000);
        drawContributions(canvasEl, {
            data: data,
            username: username,
            themeName: theme,
            footerText: `Generated by ${username}`,
        });

        const absolutePath = path.resolve(process.cwd(), outputPath);
        const buffer = canvasEl.toBuffer("image/png");

        const dir = path.dirname(absolutePath);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }
        fs.writeFileSync(absolutePath, buffer);
        core.info(`Image saved to ${absolutePath}`);

        if (!isDryRun) {
            await commitAndPush(outputPath);
        } else {
            core.info("Dry run enabled. Skipping git commit.");
        }
    } catch (error) {
        core.setFailed(error.message);
    }
}

run();
