name: Local Test
on:
  workflow_dispatch:
  push: { branches: ["main", "dev"] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action with no config
        uses: ./
        with:
          github_token: ${{ secrets.CONTRIBS_TOKEN }}

      - name: Run action with config
        uses: ./
        with:
          theme: 'dracula'
          username: 'oliverbooth'
          github_token: ${{ secrets.CONTRIBS_TOKEN }}

      