name: Local Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action with no config (dryrun)
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run action with name config (dryrun)
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: 'tomlin7'
          output_path: 'results/name.png'

      - name: Run action with theme config (dryrun)
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: 'dracula'
          output_path: 'results/theme.png'

      - name: Run action with name and theme config (dryrun)
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: 'nedpals'
          theme: 'blue'
          output_path: 'results/name-theme.png'